export const IS_LOADING = "IS_LOADING";

// Auth
export const USER_INFO = "USER_INFO";
export const USER_LOGOUT = "USER_LOGOUT";

//Home

export const GETALLSERVICES = "GETALLSERVICES";
export const USER_LIST = "USER_LIST";
export const ITEM_DETAILS = "ITEM_DETAILS";
export const EXPERT_USER_LIST = "EXPERT_USER_LIST";
export const GET_BARBER_LIST = "GET_BARBER_LIST";
export const SEARCH_LIST = "SEARCH_LIST";
export const SEARCH_STYLIST_LIST = "SEARCH_STYLIST_LIST";
export const TIME_SLOT = "TIME_SLOT";
export const MAIN_SERVICE = "MAIN_SERVICE";

//Profile
export const GET_FAQ = "GET_FAQ";
export const GET_TERMSANDCONDITIONS = "GET_TERMSANDCONDITIONS";
export const GET_PROFILE_DATA = "GET_PROFILE_DATA";

//Map
export const SETLOCATION = "SETLOCATION";
export const UPDATELOCATION = "UPDATE_LOCATION";
export const COORD = "COORD";

//offers
export const GET_ALL_OFFER = "GET_ALL_OFFER";
export const GET_ALL_OFFERS = "GET_ALL_OFFERS";
export const GET_OFFERS_LIST = "GET_OFFERS_LIST";
export const GET_USER_CAMPAIGN_LIST = "GET_USER_CAMPAIGN_LIST";
export const GET_OFFER_DETAILS = "GET_OFFER_DETAILS";

//pakages
export const GET_All_PACKAGE_LIST = "GET_All_PACKAGE_LIST";
export const GET_ALL_PACKAGES = "GET_ALL_PACKAGES";
export const GET_PACKAGES_LIST = "GET_PACKAGES_LIST";

// favourite
export const GET_USER_FAV_LIST = "GET_USER_FAV_LIST";
export const SET_FAV_USER = "SET_FAV_USER";

// appointment
export const GET_APPOINTMENTS_LIST = "GET_APPOINTMENTS_LIST";
export const APPOINTMENTS_DETAILS = "APPOINTMENTS_DETAILS";
export const GET_APPOINTMENT = "GET_APPOINTMENT";
export const APPOINTMENTS_RESCHEDULE = "APPOINTMENTS_RESCHEDULE";
export const REVIEW_LIST = "REVIEW_LIST";
export const REASON_LIST = "REASON_LIST";

// cart

export const ADD_TO_CART = "ADD_TO_CART";
export const CART_DETAILS = "CAR_TDETAILS";
export const CART_COUNT = "CART_COUNT";
export const SELECTED_SERVICE = "SELECTED_SERVICE";
export const SELECTED_TIME_SLOT = "SELECTED_TIME_SLOT";

// chat
export const GET_CHATS_PARTICIPANTS = "GET_CHATS_PARTICIPANTS";

// Address
export const GET_ADDRESS_LIST = "GET_ADDRESS_LIST";
export const LOCATION = "LOCATION";
export const SET_DEFAULT_ADDRESS = "SET_DEFAULT_ADDRESS";
