export const screenName = {
  Login: "Login",
  OptVerification: "OptVerification",
  Home: "Home",
  YourStylist: "YourStylist",
  Cart: "Cart",
  Service: "Service",
  DrawerNavigator: "DrawerNavigator",
  StackNavigator: "StackNavigator",
  BottomTabBar: "BottomTabBar",
  tab_bar_name: {
    Home: "Home",
    Offer: "Offers",
    Appointment: "Appointments",
    Package: "Packages",
    Chat: "Chats",
  },
  NewYearOffer: "NewYearOffer",
  appointmentDetails: "AppointmentDetails",
  SearchItem: "SearchItem",
  ImageDetails: "ImageDetails",
  Notifications: "Notifications",
};
