export const strings = {
  Welcome: "Welcome 👋",
  Today_is_a_new_day: "Today is a new day. It’s your day. You shape it.",
  Mobile_Number: "Mobile Number",
  Get_OTP: "Get OTP",
  Verify_OTP: "Verify OTP",
  Enter_the_6_digit: "Enter the 6-digit OTP sent to you at",
  OTP: "OTP",
  Didnt_receive_OTP: "Didn’t receive OTP?",
  Resend_OTP: "Resend OTP",
  Search_by_Stylist_Name: "Search by ‘Stylist Name’",
  Services_for_Women: "Services for Women",
  Services_for_Men: "Services for Men",
  YOUR_Stylists: "YOUR STYLISTS",
  "Allow us to access your location": "Allow us to access your location",
  "We need access to your location to show you relevant Stylists, Offers and Packages":
    "We need access to your location to show you relevant Stylists, Offers and Packages",
  "Don’t Allow": "Don’t Allow",
  Allow: "Allow",
  Offers: "Offers",
  Packages: "Packages",
  "My Work": "My Work",
  Login: "Login",
  Add: "ADD",
  "Go To Cart": "Go To Cart",
  Jobs_Done: "Jobs Done",
  Flat: "Flat",
  OFF: "OFF",
  Select_Date: "Select Date",
  Select_Time: "Select Time",
  Cart: "Cart",
  "Bill Details": "Bill Details",
  "Select Date": "Select Date",
  "Select Time": "Select Time",
  "Book  Appointment": "Book  Appointment",
  "Timing can be adjusted by calling the Stylist after Booking":
    "Timing can be adjusted by calling the Stylist after Booking",
  Cancel: "Cancel",
  Apply: "Apply",
  Cost: "Cost",
  Low_To_High: "Low To High",
  High_To_Low: "High To Low",
  All_Reviews: "All Reviews",
  Newest: "Newest",
  Highest: "Highest",
  Lowest: "Lowest",
  Jeffery_Bills: "Jeffery Bills",
  "The environment here was quiet aand relaxing.The owner who gets thiings a done was very considerate, calm, and quiet accommodating to people tyukil questions and request.":
    "The environment here was quiet aand relaxing.The owner who gets thiings a done was very considerate, calm, and quiet accommodating to people tyukil questions and request.",
  Party_Makeup: "Party Makeup",
  Nickson_John: "Nickson John",
  Account_Setting: "Account Setting",
  My_Favorites: "My Favorites",
  My_Appointments: "My Appointments",
  Notification_Settings: "Notification Settings",
  FAQ_s: "FAQ’s",
  Privacy_Policy: "Privacy Policy",
  TermsConditions: "Terms & Conditions",
  Logout: "Logout",
  Congratulation: "Congratulation",
  "You can view your booking in the appointment section.":
    "You can view your booking in the appointment section.",
  "Please pay in person to the Stylist.":
    "Please pay in person to the Stylist.",
  "Back to Home": "Back to Home",
  "Your cart is empty": "Your cart is empty",
  "Looks like you have not added anything to you cart.Go ahead & explore top categories.":
    "Looks like you have not added anything to you cart. Go ahead & explore top categories.",
  Your_Appointments: "Your Appointments",
  Select_your_City: "Select your City",
  Select_City: "Select City",
  Submit: "Submit",
  "New Year Offer": "New Year Offer",
  Availability: "Availability",
  "All Days": "All Days",
  Amenities: "Amenities",
  Majid_Khan: "Majid Khan",
  "08:30 PM": "08:30 PM",
  "26 May 2024": "26 May 2024",
  Sector_Mohali: "Sector 67, Mohali",
  haircut_Classic_shaving: "Haircut, Classic Shaving",
  "Total (INR)": "Total (INR)",
  "₹500.00": " ₹500.00",
  Past_Services: "Past Services",
  Give_Feedback: "Give Feedback",
  Completed: "Completed",
  Appointment_Detail: "Appointment Detail",
  Directions: "Directions",
  Chat: "Chat",
  Call_Stylist: "Call Stylist",
  Time: "Time",
  Date: "Date",
  "OTP to start the service": "OTP to start the service",
  Reschedule: "Reschedule",
  "Our service is available for": "Our service is available for ",
  "Chandigarh, Mohali,Kharar, Panchkula":
    "Chandigarh, Mohali,\nKharar, Panchkula ",
  Zirakpur: " Zirakpur ",
  Previous_Booking: "Previous Booking",
  "You have 1 Service Left": "You have 1 Service Left",
  Hair_color: "Hair color",
  "Book Again Your Appointment": "Book Again Your Appointment",
  Appointment_Cancellation: "Appointment Cancellation",
  "Are you sure?": "Are you sure?",
  "you want to cancel your appointment with Majid Khan?":
    "you want to cancel your appointment\nwith Majid Khan?",
  "What is the reason of cancellation?": "What is the reason of cancellation?",
  "Confirm Cancellation": "Confirm Cancellation",
  Notifications: "Notifications",
  Book_Again: "Book Again",
  Feedback: "Feedback",
  "Add a detailed review": "Add a detailed review",
  "Submit Feedback": "Submit Feedback",
  "Thank you for your valuable feedback!":
    "Thank you for your valuable\nfeedback!",
  Personal_Information: "Personal Information",
  Full_Name: "Full Name",
  Email_Address: "Email Address",
  Phone_Number: "Phone Number",
  Gender: "Gender",
  Dat_of_Birth: "Date of Birth",
  FAQ: "FAQ’S",
  "All Notifications": "All Notifications",
  "Mark all as read": "Mark all as read",
  Messages: "Messages",
  All: "All",
  Unread: "Unread",
  "Flat No. 14, Ansal Palm Grove, Mohali":
    "Flat No. 14, Ansal Palm Grove, Mohali",
  " My Stylist, collects personal information including names, email addresses, phone numbers, and location data to personalize user experiences and improve service quality. Usage data and device information are also gathered to analyze user behavior and ensure application compatibility. This information may be shared with third-party service providers for operational purposes or in the event of business transfers. We prioritize data security and take measures to protect information from unauthorized access or disclosure. Changes to our privacy policy will be promptly communicated, and users are encouraged to review updates periodically. For inquiries or concerns regarding our privacy practices, please contact us.":
    " \t \tMy Stylist, collects personal information including names, email addresses, phone numbers, and location data to personalize user experiences and improve service quality. Usage data and device information are also gathered to analyze user behavior and ensure application compatibility. This information may be shared with third-party service providers for operational purposes or in the event of business transfers. We prioritize data security and take measures to protect information from unauthorized access or disclosure. Changes to our privacy policy will be promptly communicated, and users are encouraged to review updates periodically. For inquiries or concerns regarding our privacy practices, please contact us. My Stylist, is committed to safeguarding the privacy of our users. In addition to collecting personal information for enhancing user experiences and analyzing usage patterns, we prioritize transparency and accountability in our data practices. We may utilize collected information to tailor services, communicate updates or promotional offers, and ensure legal compliance. Rest assured, stringent security measures are implemented to prevent unauthorized access, alteration, or disclosure of your data. We continuously review and update our privacy policy to reflect evolving user needs and regulatory requirements. For any queries or concerns regarding your privacy, please feel free to reach out to us for further assistance.",
  "By accessing and using My Stylist, the barber application provided by [Your Company Name], you agree to adhere to the following terms and conditions. You must be at least 18 years old to use the application, and by doing so, you confirm that you have the legal capacity to enter into binding agreements. When creating a user account, you are responsible for maintaining the confidentiality of your account information and for all activities conducted under your account. My Stylist reserves the right to suspend or terminate accounts found in violation of these terms or engaging in unlawful activities. The content provided within the application, including but not limited to text, images, and graphics, is for informational purposes only and should not be considered professional advice. You agree to use My Stylist solely for lawful purposes and not to engage in any activity that may harm, disrupt, or impair the application's functionality or integrity. The Company reserves the right to modify, suspend, or discontinue any aspect of My Stylist at any time without prior notice. Your continued use of the application following any changes constitutes acceptance of those changes. These terms and conditions constitute the entire agreement between you and the Company regarding your use of My Stylist and supersede any prior agreements or understandings. If you have any questions or concerns about these terms, please contact us for further assistance.":
    " \t \tBy accessing and using My Stylist, the barber application provided by [Your Company Name], you agree to adhere to the following terms and conditions. You must be at least 18 years old to use the application, and by doing so, you confirm that you have the legal capacity to enter into binding agreements. When creating a user account, you are responsible for maintaining the confidentiality of your account information and for all activities conducted under your account. My Stylist reserves the right to suspend or terminate accounts found in violation of these terms or engaging in unlawful activities. The content provided within the application, including but not limited to text, images, and graphics, is for informational purposes only and should not be considered professional advice. You agree to use My Stylist solely for lawful purposes and not to engage in any activity that may harm, disrupt, or impair the application's functionality or integrity. The Company reserves the right to modify, suspend, or discontinue any aspect of My Stylist at any time without prior notice. Your continued use of the application following any changes constitutes acceptance of those changes. These terms and conditions constitute the entire agreement between you and the Company regarding your use of My Stylist and supersede any prior agreements or understandings. If you have any questions or concerns about these terms, please contact us for further assistance.",
  "What are your hours of operation?": "What are your hours of operation?",
  "Our barbershop operates from 10 AM to 9 PM, Monday through Saturday. We're closed on Sundays. You can book appointments online or give us a call during our operating hours. Walk-ins are also welcome, but appointments are recommended to ensure availability. Please note that our hours may vary during holidays or special occasions.":
    "Our barbershop operates from 10 AM to 9 PM, Monday through Saturday. We're closed on Sundays. You can book appointments online or give us a call during our operating hours. Walk-ins are also welcome, but appointments are recommended to ensure availability. Please note that our hours may vary during holidays or special occasions.",
  Confirm_location: "Confirm location",
  Enter_here: "Enter here",
  "Select a location": "Select a location",
  "Search for area, street name...": "Search for area, street name...",
  "Use my current location": "Use my current location",
  "Add new address": "Add new address",
  "SAVED ADDRESSES": "SAVED ADDRESSES",
  Edit: "Edit",
  Delete: "Delete",
  "Confirm your address": "Confirm your address",
  "Edit complete address": "Edit complete address",
  "Save address as": "Save address as",
  Home: "Home",
  Other: "Other",
  Work: "Work",
  "Enter here": "Enter here",
  "House / Flat No.": "House / Flat No.",
  "Sector / Block": "Sector / Block",
  "Landmark (optional)": "Landmark (optional)",
  "Save address": "Save address",
};
