export const strings = {
  Welcome: "Welcome 👋",
  Today_is_a_new_day: "Today is a new day. It’s your day. You shape it.",
  Mobile_Number: "Mobile Number",
  Get_OTP: "Get OTP",
  Verify_OTP: "Verify OTP",
  Enter_the_6_digit: "Enter the 6-digit OTP sent to you at",
  OTP: "OTP",
  Didnt_receive_OTP: "Didn’t receive OTP?",
  Resend_OTP: "Resend OTP",
  Search_by_Stylist_Name: "Search by ‘Stylist Name’",
  Services_for_Women: "Services for Women",
  Services_for_Men: "Services for Men",
  YOUR_Stylists: "YOUR STYLISTS",
  "Allow us to access your location": "Allow us to access your location",
  "We need access to your location to show you relevant Stylists, Offers and Packages":
    "We need access to your location to show you relevant Stylists, Offers and Packages",

  "Don’t Allow": "Don’t Allow",
  Allow: "Allow",
  Offers: "Offers",
  Packages: "Packages",
  "My Work": "My Work",
  Login: "Login",
  Add: "ADD",
  "Go To Cart": "Go To Cart",
  Jobs_Done: "Jobs Done",
  Flat: "Flat",
  OFF: "OFF",
  Select_Date: "Select Date",
  Select_Time: "Select Time",
  Cart: "Cart",
  "Bill Details": "Bill Details",
  "Select Date": "Select Date",
  "Select Time": "Select Time",
  "Book  Appointment": "Book  Appointment",
};
