export const strings = {
  Welcome: "Welcome 👋",
  Today_is_a_new_day: "Today is a new day. It’s your day. You shape it.",
  Mobile_Number: "Mobile Number",
  Get_OTP: "Get OTP",
  Verify_OTP: "Verify OTP",
  Enter_the_6_digit: "Enter the 6-digit OTP sent to you at",
  OTP: "OTP",
  Didnt_receive_OTP: "Didn’t receive OTP?",
  Resend_OTP: "Resend OTP",
  Search_by_Stylist_Name: "Search by ‘Stylist Name’",
  Services_for_Women: "Services for Women",
  Services_for_Men: "Services for Men",
  YOUR_Stylists: "YOUR STYLISTS",
  "Allow us to access your location": "Allow us to access your location",
  "We need access to your location to show you relevant Stylists, Offers and Packages":
    "We need access to your location to show you relevant Stylists, Offers and Packages",
  "Don’t Allow": "Don’t Allow",
  Allow: "Allow",
  Offers: "Offers",
  Packages: "Packages",
  "My Work": "My Work",
  Login: "Login",
  Add: "ADD",
  "Go To Cart": "Go To Cart",
  Jobs_Done: "Jobs Done",
  Flat: "Flat",
  OFF: "OFF",
  Select_Date: "Select Date",
  Select_Time: "Select Time",
  Cart: "Cart",
  "Bill Details": "Bill Details",
  "Select Date": "Select Date",
  "Select Time": "Select Time",
  "Book  Appointment": "Book  Appointment",
  "Timing can be adjusted by calling the Stylist after Booking":
    "Timing can be adjusted by calling the Stylist after Booking",
  Cancel: "Cancel",
  Apply: "Apply",
  Cost: "Cost",
  Low_To_High: "Low To High",
  High_To_Low: "High To Low",
  All_Reviews: "All Reviews",
  Newest: "Newest",
  Highest: "Highest",
  Lowest: "Lowest",
  Jeffery_Bills: "Jeffery Bills",
  "The environment here was quiet aand relaxing.The owner who gets thiings a done was very considerate, calm, and quiet accommodating to people tyukil questions and request.":
    "The environment here was quiet aand relaxing.The owner who gets thiings a done was very considerate, calm, and quiet accommodating to people tyukil questions and request.",
  Party_Makeup: "Party Makeup",
  Nickson_John: "Nickson John",
  Account_Setting: "Account Setting",
  My_Favorites: "My Favorites",
  My_Appointments: "My Appointments",
  Notification_Settings: "Notification Settings",
  FAQ_s: "FAQ’s",
  Privacy_Policy: "Privacy Policy",
  TermsConditions: "Terms & Conditions",
  Logout: "Logout",
  Congratulation: "Congratulation",
  "You can view your booking in the appointment section.":
    "You can view your booking in the appointment section.",
  "Please pay in person to the Stylist.":
    "Please pay in person to the Stylist.",
  "Back to Home": "Back to Home",
  "Your cart is empty": "Your cart is empty",
  "Looks like you have not added anything to you cart.Go ahead & explore top categories.":
    "Looks like you have not added anything to you cart. Go ahead & explore top categories.",
  Your_Appointments: "Your Appointments",
  Select_your_City: "Select your City",
  Select_City: "Select City",
  Submit: "Submit",
  "New Year Offer": "New Year Offer",
  Availability: "Availability",
  "All Days": "All Days",
  Amenities: "Amenities",
  Majid_Khan: "Majid Khan",
  "08:30 PM": "08:30 PM",
  "26 May 2024": "26 May 2024",
  Sector_Mohali: "Sector 67, Mohali",
  haircut_Classic_shaving: "Haircut, Classic Shaving",
  "Total (INR)": "Total (INR)",
  "₹500.00": " ₹500.00",
  Past_Services: "Past Services",
  Give_Feedback: "Give Feedback",
  Completed: "Completed",
  Appointment_Detail: "Appointment Detail",
  Directions: "Directions",
  Chat: "Chat",
  Call_Stylist: "Call Stylist",
  Time: "Time",
  Date: "Date",
  "OTP to start the service": "OTP to start the service",
  Reschedule: "Reschedule",
  "Our service is available for": "Our service is available for ",
  "Chandigarh, Mohali,Kharar, Panchkula":
    "Chandigarh, Mohali,\nKharar, Panchkula ",
  Zirakpur: " Zirakpur ",
  Previous_Booking: "Previous Booking",
  "You have 1 Service Left": "You have 1 Service Left",
  Hair_color: "Hair color",
  "Book Again Your Appointment": "Book Again Your Appointment",
  Appointment_Cancellation: "Appointment Cancellation",
  "Are you sure?": "Are you sure?",
  "you want to cancel your appointment with Majid Khan?":
    "you want to cancel your appointment\nwith Majid Khan?",
  "What is the reason of cancellation?": "What is the reason of cancellation?",
  "Confirm Cancellation": "Confirm Cancellation",
};
